behaviors:
  SecurityGuard:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1200
      learning_rate: 3.0e-4
      beta: 5.0e-4
      num_epoch: 3
      epsilon: 0.2
      lambd: 0.95
    network_settings:
      num_layers: 2
      hidden_units: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 1000
